PRESET_STYLES = [
    {
        "name": "clean-student-print",
        "sample_text": "Clean student notebook print",
        "slant_degrees": -1.0,
        "stroke_width": 2.0,
        "letter_spacing": 1.4,
        "word_spacing": 18.0,
        "baseline_jitter": 0.55,
        "pressure_variance": 0.08,
        "size_scale": 1.0,
        "seed_bias": 0.42,
        "roundness": 0.62,
        "connectedness": 0.18,
        "tallness": 0.98,
        "chaos": 0.06,
        "angle_variance": 0.03,
    },
    {
        "name": "soft-journal",
        "sample_text": "Soft rounded personal journal handwriting",
        "slant_degrees": 4.0,
        "stroke_width": 2.15,
        "letter_spacing": 0.7,
        "word_spacing": 17.0,
        "baseline_jitter": 0.75,
        "pressure_variance": 0.12,
        "size_scale": 1.04,
        "seed_bias": 0.46,
        "roundness": 0.88,
        "connectedness": 0.28,
        "tallness": 1.02,
        "chaos": 0.08,
        "angle_variance": 0.04,
    },
    {
        "name": "modern-cursive",
        "sample_text": "Smooth modern cursive for cards and notes",
        "slant_degrees": 10.0,
        "stroke_width": 1.95,
        "letter_spacing": -0.9,
        "word_spacing": 17.0,
        "baseline_jitter": 0.9,
        "pressure_variance": 0.14,
        "size_scale": 1.07,
        "seed_bias": 0.48,
        "roundness": 0.78,
        "connectedness": 0.82,
        "tallness": 1.12,
        "chaos": 0.1,
        "angle_variance": 0.05,
    },
    {
        "name": "signature-flow",
        "sample_text": "Elegant flowing signature-like handwriting",
        "slant_degrees": 14.0,
        "stroke_width": 1.85,
        "letter_spacing": -1.1,
        "word_spacing": 18.0,
        "baseline_jitter": 0.7,
        "pressure_variance": 0.18,
        "size_scale": 1.12,
        "seed_bias": 0.5,
        "roundness": 0.7,
        "connectedness": 0.9,
        "tallness": 1.2,
        "chaos": 0.08,
        "angle_variance": 0.05,
    },
    {
        "name": "premium-print",
        "sample_text": "Polished upright print for professional notes",
        "slant_degrees": -3.0,
        "stroke_width": 2.05,
        "letter_spacing": 1.8,
        "word_spacing": 19.0,
        "baseline_jitter": 0.45,
        "pressure_variance": 0.09,
        "size_scale": 1.01,
        "seed_bias": 0.4,
        "roundness": 0.52,
        "connectedness": 0.16,
        "tallness": 0.97,
        "chaos": 0.05,
        "angle_variance": 0.025,
    },
    {
        "name": "friendly-notes",
        "sample_text": "Readable human note-taking style",
        "slant_degrees": 3.0,
        "stroke_width": 2.1,
        "letter_spacing": 0.9,
        "word_spacing": 17.0,
        "baseline_jitter": 0.85,
        "pressure_variance": 0.13,
        "size_scale": 1.03,
        "seed_bias": 0.46,
        "roundness": 0.72,
        "connectedness": 0.34,
        "tallness": 1.0,
        "chaos": 0.09,
        "angle_variance": 0.04,
    },
    {
        "name": "architect-print",
        "sample_text": "Technical all-purpose print with clean spacing",
        "slant_degrees": 0.0,
        "stroke_width": 1.9,
        "letter_spacing": 2.1,
        "word_spacing": 20.0,
        "baseline_jitter": 0.35,
        "pressure_variance": 0.07,
        "size_scale": 0.98,
        "seed_bias": 0.38,
        "roundness": 0.36,
        "connectedness": 0.08,
        "tallness": 0.94,
        "chaos": 0.04,
        "angle_variance": 0.02,
    },
    {
        "name": "warm-correspondence",
        "sample_text": "Warm handwritten letter style",
        "slant_degrees": 7.0,
        "stroke_width": 2.0,
        "letter_spacing": 0.5,
        "word_spacing": 18.0,
        "baseline_jitter": 0.8,
        "pressure_variance": 0.15,
        "size_scale": 1.08,
        "seed_bias": 0.47,
        "roundness": 0.8,
        "connectedness": 0.46,
        "tallness": 1.1,
        "chaos": 0.09,
        "angle_variance": 0.04,
    },
]
